"""ERC-721 metadata generation for booth NFTs."""

from __future__ import annotations

import base64
import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def generate_metadata(
    booth: dict[str, Any],
    scene_spec: dict[str, Any],
    render_image_path: Path | None = None,
) -> dict[str, Any]:
    """Generate ERC-721 metadata JSON for a single booth NFT.

    Args:
        booth: Booth dict from scene_spec with 'id', 'nft', etc.
        scene_spec: Full scene specification for context.
        render_image_path: Path to the gallery render PNG (optional).

    Returns:
        ERC-721 compliant metadata dict.
    """
    nft: dict[str, Any] = booth.get("nft", {})
    theme: str = scene_spec.get("theme_name", "Virtual Gallery")
    palette: list[str] = scene_spec.get("global_color_palette", [])

    name: str = nft.get("name", "Untitled")
    collection: str = nft.get("collection", "World Builder")
    art_style: str = nft.get("art_style", "gradient_noise")
    art_seed: int = nft.get("art_seed", 0)
    art_colors: list[str] = nft.get("art_colors", [])
    booth_id: str = booth.get("id", "unknown")

    # Build image data URI from render.png
    image_uri: str = ""
    if render_image_path and render_image_path.exists():
        try:
            img_bytes = render_image_path.read_bytes()
            img_b64 = base64.b64encode(img_bytes).decode("utf-8")
            image_uri = f"data:image/png;base64,{img_b64}"
        except Exception as e:
            logger.warning(f"[Metadata] Failed to encode render image: {e}")
            image_uri = _placeholder_svg(name)
    else:
        image_uri = _placeholder_svg(name)

    attributes = [
        {"trait_type": "Collection", "value": collection},
        {"trait_type": "Art Style", "value": art_style},
        {"trait_type": "Art Seed", "value": art_seed, "display_type": "number"},
        {"trait_type": "Booth ID", "value": booth_id},
        {"trait_type": "Gallery Theme", "value": theme},
        {"trait_type": "Color Palette", "value": ", ".join(art_colors[:4])},
    ]

    if palette:
        attributes.append({"trait_type": "Gallery Palette", "value": ", ".join(palette[:3])})

    return {
        "name": f"{name} — {theme}",
        "description": (
            f"NFT artwork '{name}' from the '{collection}' collection, "
            f"displayed in the '{theme}' virtual gallery. "
            f"Generated by GLM-5.1 AI World Builder with {art_style} style."
        ),
        "image": image_uri,
        "external_url": "",
        "attributes": attributes,
    }


def save_metadata_files(
    scene_spec: dict[str, Any],
    render_path: Path,
    output_dir: Path,
) -> list[Path]:
    """Generate and save metadata JSON files for all booths.

    Args:
        scene_spec: Full scene specification.
        render_path: Path to render.png.
        output_dir: Directory to write metadata JSON files.

    Returns:
        List of paths to the created metadata files.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    booths: list[dict] = scene_spec.get("booths", [])
    saved: list[Path] = []

    for i, booth in enumerate(booths):
        metadata = generate_metadata(booth, scene_spec, render_path)
        booth_id = booth.get("id", f"booth_{i}")
        filename = f"{booth_id}_metadata.json"
        filepath = output_dir / filename

        filepath.write_text(
            json.dumps(metadata, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        saved.append(filepath)

    logger.info(f"[Metadata] Saved {len(saved)} metadata files to {output_dir}")
    return saved


def _placeholder_svg(name: str) -> str:
    """Generate a minimal SVG placeholder as a data URI."""
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="512" height="640">'
        f'<rect width="512" height="640" fill="#1a1a2e"/>'
        f'<text x="256" y="320" text-anchor="middle" fill="#e2e8f0" '
        f'font-size="24" font-family="sans-serif">{name[:30]}</text>'
        f'</svg>'
    )
    b64 = base64.b64encode(svg.encode("utf-8")).decode("utf-8")
    return f"data:image/svg+xml;base64,{b64}"
